[package]
name = "RustIOT"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-modbus = { version = "0.7", features = ["tcp"] }
rumqttc = "0.25"
tokio-tungstenite = "0.24"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum = "0.8.7"
rust-embed = "8.9.0"
tower-http = "0.6.8"